# SPDX-License-Identifier: Apache-2.0
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aegis-fraudstream.fullname" . }}
spec:
  podSelector:
    matchLabels: {{- include "aegis-fraudstream.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
