# SPDX-License-Identifier: Apache-2.0
schemaVersion: '2.0.0'
metadataTest:
  exposedPorts: ['8080']
  entrypoint: ['uvicorn','aegis_fraudstream.app:app','--host','0.0.0.0','--port','8080']
  user: '10001|nonroot'
