# SPDX-License-Identifier: Apache-2.0
name: Bug report
description: Report a problem
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes: { label: What happened?, description: Describe the issue }
    validations: { required: true }
