# SPDX-License-Identifier: Apache-2.0
version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: aegis-dev:latest
    environment:
      - AEGIS_ENV=production
      - AEGIS_LOG_LEVEL=INFO
      - AEGIS_REDIS_URL=redis://redis:6379/0
    ports: ["8080:8080"]
    depends_on: [redis]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:10.4.5
    ports: ["3000:3000"]
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/prom.yml:ro
