# SPDX-License-Identifier: Apache-2.0
version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      AEGIS_ENV: development
      AEGIS_ENABLE_DOCS: "true"
      AEGIS_REDIS_URL: redis://redis:6379/0
      AEGIS_DB_URL: postgresql://postgres:postgres@db:5432/aegis
    ports: ["8080:8080"]
    depends_on: [redis, db]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  db:
    image: postgres:16-alpine
    environment: { POSTGRES_PASSWORD: postgres, POSTGRES_DB: aegis }
    ports: ["5432:5432"]
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:11.0.0
    ports: ["3000:3000"]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/dashboards:/var/lib/grafana/dashboards
