# SPDX-License-Identifier: Apache-2.0
image:
  repository: ghcr.io/your-org/aegis-fraudstream
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 2
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
env:
  - name: LOG_LEVEL
    value: info

serviceAccount:
  create: true
  name: ""
  annotations: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
podSecurityContext:
  fsGroup: 10001
