# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Aegis FraudStream Authors

openapi: 3.0.3
info: {title: Aegis FraudStream API, version: 1.3.0}
