# SPDX-License-Identifier: Apache-2.0
groups:
- name: aegis
  rules:
  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
    for: 10m
    labels: { severity: page }
    annotations: { summary: "5xx > 5% for 10m" }
  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(aegis_inference_seconds_bucket[5m])) > 0.2
    for: 10m
    labels: { severity: page }
    annotations: { summary: "p95 inference latency > 200ms" }
  - alert: Many429
    expr: sum(rate(http_requests_total{status="429"}[5m])) > 5
    for: 10m
    labels: { severity: warn }
    annotations: { summary: "Excess 429 responses" }
