# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: build_wheels-${{ github.ref }}
  cancel-in-progress: true
name: Build Wheels
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip cibuildwheel build
      - run: cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*
