# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: build_sign-${{ github.ref }}
  cancel-in-progress: true
name: Build, Push, and Sign
on:
  push:
    branches: [main]
    tags: ['v*.*.*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Cosign install
        uses: sigstore/cosign-installer@v3.5.0
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/${{ github.repository }}:latest --yes
