# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: commitlint-${{ github.ref }}
  cancel-in-progress: true
name: Commitlint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: wagoid/commitlint-github-action@v6
