# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: dependency_review-${{ github.ref }}
  cancel-in-progress: true
name: Dependency Review
on: [pull_request]
permissions: { contents: read }
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
