# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: docker_publish-${{ github.ref }}
  cancel-in-progress: true
name: Docker Publish
on:
  push: { branches: [main] }
  release: { types: [created] }
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Cosign Sign (optional)
        if: ${{ secrets.COSIGN_PRIVATE_KEY != '' }}
        uses: sigstore/cosign-installer@v3
        with: { cosign-release: 'v2.2.4' }
      - if: ${{ secrets.COSIGN_PRIVATE_KEY != '' }}
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          TAGS: ${{ steps.meta.outputs.tags }}


# Keyless signing and attestation (Sigstore OIDC)
- name: Install Cosign
  uses: sigstore/cosign-installer@v3
  with: { cosign-release: 'v2.2.4' }
- name: Keyless sign image
  env:
    COSIGN_EXPERIMENTAL: "1"
  run: |
    for t in ${{ steps.meta.outputs.tags }}; do
      cosign sign --yes $t
      cosign attest --yes --predicate sbom-spdx.json --type spdx $t || true
    done
