# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true
name: Docs
on:
  push:
    branches: [main]
    paths: ["docs/**","mkdocs.yml","scripts/generate_openapi.py"]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install mkdocs-material pyyaml
      - run: python scripts/generate_openapi.py
      - run: mkdocs build --strict
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
