# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: fuzz-${{ github.ref }}
  cancel-in-progress: true
name: Fuzz
on: [push, pull_request]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip uv atheris
      - run: uv pip install -e ".[dev]" --system
      - run: python -m tests.fuzz.fuzz_event -runs=10000
