# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: gh_pages-${{ github.ref }}
  cancel-in-progress: true
name: Docs
on:
  push: { branches: ["main"] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install mkdocs-material
      - run: python scripts/openapi_export.py openapi.json
      - run: mkdocs gh-deploy --force
