# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true
name: Gitleaks
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with: { args: "--redact" }
