# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: hadolint-${{ github.ref }}
  cancel-in-progress: true
name: Hadolint
on: [push, pull_request]
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile
