# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: labeler-${{ github.ref }}
  cancel-in-progress: true
name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions: { pull-requests: write, contents: read }
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
