# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: locust_smoke-${{ github.ref }}
  cancel-in-progress: true
name: Load Smoke
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -e .[dev]
      - run: uvicorn aegis_fraudstream.app:app --port 8080 &
      - run: sleep 2 && locust -f locustfile.py --headless -u 20 -r 20 -t 10s --host http://127.0.0.1:8080
