# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: mypy-${{ github.ref }}
  cancel-in-progress: true
name: mypy
on: [push, pull_request]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -e .[dev] mypy
      - run: mypy
