# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: pre_commit-${{ github.ref }}
  cancel-in-progress: true
name: pre-commit
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: pre-commit/action@v3.0.1
