# SPDX-License-Identifier: Apache-2.0
name: PyPI Publish
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          skip-existing: true
