# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: true
name: Publish to PyPI
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install build twine
      - run: python -m build
      - env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
