# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: redoc-${{ github.ref }}
  cancel-in-progress: true
name: ReDoc
on:
  push:
    branches: [main]
    paths: ["docs/openapi.gen.*"]
jobs:
  redoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g redoc-cli
      - run: redoc-cli bundle docs/openapi.gen.yaml -o site/redoc.html
      - uses: actions/upload-pages-artifact@v3
        with: { path: site }
      - uses: actions/deploy-pages@v4
