# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: ruff-${{ github.ref }}
  cancel-in-progress: true
name: ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with: { src: "aegis_fraudstream" }
