# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: scorecards-${{ github.ref }}
  cancel-in-progress: true
name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule: [{ cron: '20 12 * * 1' }]
  push: { branches: [main] }
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
