# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: semantic_pr-${{ github.ref }}
  cancel-in-progress: true
name: Semantic PR
on: [pull_request_target]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
