# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: stale-${{ github.ref }}
  cancel-in-progress: true
name: Close Stale Issues
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Stale issue. Please update or it will be closed.'
          days-before-stale: 60
          days-before-close: 14
