# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: tfsec-${{ github.ref }}
  cancel-in-progress: true
name: tfsec
on: [push, pull_request]
jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra/terraform
          additional_args: --soft-fail
