# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: trivy-${{ github.ref }}
  cancel-in-progress: true
name: Trivy Scan
on: [push, pull_request]
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
