# SPDX-License-Identifier: Apache-2.0
concurrency:
  group: trufflehog-${{ github.ref }}
  cancel-in-progress: true
name: TruffleHog
on: [push, pull_request]
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: trufflesecurity/trufflehog@v3.81.7
        with:
          path: .
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
